export const jwtConstants = {
    secret: 'eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4MTQyNjM4OCwiaWF0IjoxNjgxNDI2Mzg4fQ.ziig15MUJYLH53N0WeTtRF_Xkllm_gQeRJxTN6UIUCo',
}